c="akhila"
# print(c[ : : ])
# print(c[0 : : 1])
# print(c[ : : 2])
# print(c[ : : 3])
# print(c[ : : 4])
# print(c[ : : 5])
# print(c[ : : 6])
# print(c[ : : 7])

c="akhila"
# print(c[ : : -1])
# print(c[ : : -2])
# print(c[ : : -3])
# print(c[ : : -4])
# print(c[ : : -5])
# print(c[ : : -6])
# print(c[ : : -7])

c="akhila"
# print(c[1 : :])
# print(c[2 : :])
# print(c[3 : :])
# print(c[4 : :])
# print(c[5 : :])
# print(c[6 : :])
# print(c[1: 6: ])
# print(c[2: 5: ])
# print(c[3: 4: ])
# print(c[4: 3: ])
# print(c[5: 2: ])
# print(c[6: 1: ])
# print(c[7: 0: ])
